// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_leafcloud_app/test/widgets/ph_monitor_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:flutter_leafcloud_app/models/ph_sensor_data.dart' as _i3;
import 'package:flutter_leafcloud_app/notifiers/ph_monitor_notifier.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PHMonitorNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPHMonitorNotifier extends _i1.Mock implements _i2.PHMonitorNotifier {
  MockPHMonitorNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.PHSensorData> get readings =>
      (super.noSuchMethod(
            Invocation.getter(#readings),
            returnValue: <_i3.PHSensorData>[],
          )
          as List<_i3.PHSensorData>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isReconnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isReconnecting),
            returnValue: false,
          )
          as bool);

  @override
  bool get isMonitoring =>
      (super.noSuchMethod(Invocation.getter(#isMonitoring), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void connect(String? url) => super.noSuchMethod(
    Invocation.method(#connect, [url]),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
