// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_leafcloud_app/test/widgets/video_feed_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i5;

import 'package:flutter_leafcloud_app/models/ph_sensor_data.dart' as _i4;
import 'package:flutter_leafcloud_app/notifiers/bucket_control_notifier.dart'
    as _i6;
import 'package:flutter_leafcloud_app/notifiers/ph_monitor_notifier.dart'
    as _i3;
import 'package:flutter_leafcloud_app/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PHMonitorNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPHMonitorNotifier extends _i1.Mock implements _i3.PHMonitorNotifier {
  MockPHMonitorNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.PHSensorData> get readings =>
      (super.noSuchMethod(
            Invocation.getter(#readings),
            returnValue: <_i4.PHSensorData>[],
          )
          as List<_i4.PHSensorData>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isReconnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isReconnecting),
            returnValue: false,
          )
          as bool);

  @override
  bool get isMonitoring =>
      (super.noSuchMethod(Invocation.getter(#isMonitoring), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void connect(String? url) => super.noSuchMethod(
    Invocation.method(#connect, [url]),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BucketControlNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockBucketControlNotifier extends _i1.Mock
    implements _i6.BucketControlNotifier {
  MockBucketControlNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  String get activeBucketStatus =>
      (super.noSuchMethod(
            Invocation.getter(#activeBucketStatus),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#activeBucketStatus),
            ),
          )
          as String);

  @override
  bool get phUpdateRequested =>
      (super.noSuchMethod(
            Invocation.getter(#phUpdateRequested),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> setActiveBucket(String? label) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveBucket, [label]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setExperimentId(String? experimentId) =>
      (super.noSuchMethod(
            Invocation.method(#setExperimentId, [experimentId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchActiveBucketStatus() =>
      (super.noSuchMethod(
            Invocation.method(#fetchActiveBucketStatus, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> togglePHSession() =>
      (super.noSuchMethod(
            Invocation.method(#togglePHSession, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> restartIot() =>
      (super.noSuchMethod(
            Invocation.method(#restartIot, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void startPolling({Duration? interval = const Duration(seconds: 2)}) =>
      super.noSuchMethod(
        Invocation.method(#startPolling, [], {#interval: interval}),
        returnValueForMissingStub: null,
      );

  @override
  void stopPolling() => super.noSuchMethod(
    Invocation.method(#stopPolling, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
