// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_leafcloud_app/test/notifiers/image_management_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_leafcloud_app/models/image_info.dart' as _i7;
import 'package:flutter_leafcloud_app/models/sensor_data.dart' as _i3;
import 'package:flutter_leafcloud_app/services/api_service.dart' as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSensorData_1 extends _i1.SmartFake implements _i3.SensorData {
  _FakeSensorData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i6.Future<_i3.SensorData> fetchSensorData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSensorData, []),
            returnValue: _i6.Future<_i3.SensorData>.value(
              _FakeSensorData_1(this, Invocation.method(#fetchSensorData, [])),
            ),
          )
          as _i6.Future<_i3.SensorData>);

  @override
  _i6.Future<void> postActiveBucket(String? label) =>
      (super.noSuchMethod(
            Invocation.method(#postActiveBucket, [label]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> postActiveExperiment(String? experimentId) =>
      (super.noSuchMethod(
            Invocation.method(#postActiveExperiment, [experimentId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> fetchActiveBucketStatus() =>
      (super.noSuchMethod(
            Invocation.method(#fetchActiveBucketStatus, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> fetchExperimentHistory(
    String? experimentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExperimentHistory, [experimentId]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i7.ImageInfo>> fetchImages({
    int? skip = 0,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchImages, [], {#skip: skip, #limit: limit}),
            returnValue: _i6.Future<List<_i7.ImageInfo>>.value(
              <_i7.ImageInfo>[],
            ),
          )
          as _i6.Future<List<_i7.ImageInfo>>);

  @override
  _i6.Future<void> deleteImage(String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [filename]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restartIot() =>
      (super.noSuchMethod(
            Invocation.method(#restartIot, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> requestPHUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#requestPHUpdate, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> acknowledgePHUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgePHUpdate, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
